"use server";

import { headers } from "next/headers";
import { getAdminClient } from "@/lib/supabase/admin";
import { sendEmail } from "@/lib/email/nodemailer";
import {
  getGuestServiceRequestEmailHtml,
  getGuestServiceRequestEmailText,
} from "@/lib/email/service-request-templates";
import {
  guestServiceRequestSchema,
  trackingSerialSchema,
  type GuestServiceRequestInput,
  type TrackingSerialInput,
} from "@/lib/validations/service-request";
import {
  serviceRequestLimiter,
  getClientIp,
  formatTimeRemaining,
} from "@/lib/rate-limit/service-request-limiter";
import type { ServiceRequest, ServiceRequestTracking } from "@/types";

interface SubmitGuestServiceRequestResult {
  success: boolean;
  trackingSerial?: string;
  error?: string;
  rateLimitInfo?: {
    remaining: number;
    resetAt: number;
    resetIn: string;
  };
}

/**
 * Submit a guest service request without authentication
 * Generates a tracking serial and sends confirmation email
 */
export async function submitGuestServiceRequest(
  input: GuestServiceRequestInput
): Promise<SubmitGuestServiceRequestResult> {
  try {
    // 1. Validate input
    const validatedData = guestServiceRequestSchema.parse(input);

    // 2. Get client IP and user agent for rate limiting and security
    const headersList = await headers();
    const ipAddress = getClientIp(headersList);
    const userAgent = headersList.get("user-agent") || "unknown";

    console.log(
      "[GuestServiceRequest] ▶ Starting for:",
      validatedData.guest_email,
      "from IP:",
      ipAddress
    );

    // 3. Check rate limits
    const ipLimit = serviceRequestLimiter.checkIpLimit(ipAddress);
    const emailLimit = serviceRequestLimiter.checkEmailLimit(
      validatedData.guest_email
    );

    if (!ipLimit.allowed) {
      console.warn(
        "[GuestServiceRequest] ⚠️ IP rate limit exceeded:",
        ipAddress
      );
      return {
        success: false,
        error: `Too many requests from your location. Please try again in ${formatTimeRemaining(ipLimit.resetAt)}.`,
        rateLimitInfo: {
          remaining: ipLimit.remaining,
          resetAt: ipLimit.resetAt,
          resetIn: formatTimeRemaining(ipLimit.resetAt),
        },
      };
    }

    if (!emailLimit.allowed) {
      console.warn(
        "[GuestServiceRequest] ⚠️ Email rate limit exceeded:",
        validatedData.guest_email
      );
      return {
        success: false,
        error: `Too many requests from this email address. Please try again in ${formatTimeRemaining(emailLimit.resetAt)}.`,
        rateLimitInfo: {
          remaining: emailLimit.remaining,
          resetAt: emailLimit.resetAt,
          resetIn: formatTimeRemaining(emailLimit.resetAt),
        },
      };
    }

    // 4. Insert service request (tracking_serial will be auto-generated by trigger)
    const supabaseAdmin = getAdminClient();

    const { data: serviceRequest, error: insertError } = await supabaseAdmin
      .from("service_requests")
      .insert({
        client_id: null, // Guest submission
        guest_email: validatedData.guest_email,
        guest_name: validatedData.guest_name,
        guest_phone: validatedData.guest_phone || null,
        title: validatedData.title,
        description: validatedData.description,
        project_type: validatedData.project_type || null,
        dimensions: validatedData.dimensions || null,
        constraints: validatedData.constraints || null,
        budget_range: validatedData.budget_range || null,
        preferred_contact: validatedData.preferred_contact,
        status: "submitted",
        ip_address: ipAddress,
        user_agent: userAgent,
      })
      .select("tracking_serial")
      .single();

    if (insertError || !serviceRequest?.tracking_serial) {
      console.error(
        "[GuestServiceRequest] ❌ Insert error:",
        insertError?.message
      );
      throw new Error(
        "Failed to create service request. Please try again later."
      );
    }

    const trackingSerial = serviceRequest.tracking_serial;
    console.log(
      "[GuestServiceRequest] ✅ Request created with serial:",
      trackingSerial
    );

    // 5. Record submission for rate limiting
    serviceRequestLimiter.recordSubmission(
      ipAddress,
      validatedData.guest_email
    );

    // 6. Send confirmation email (non-blocking)
    const siteUrl =
      process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
    const trackingUrl = `${siteUrl}/track/${trackingSerial}`;
    const createAccountUrl = `${siteUrl}/sign-up?email=${encodeURIComponent(validatedData.guest_email)}&tracking=${trackingSerial}`;

    const emailHtml = getGuestServiceRequestEmailHtml({
      guestName: validatedData.guest_name,
      trackingSerial,
      projectTitle: validatedData.title,
      trackingUrl,
      siteUrl,
      createAccountUrl,
    });

    const emailText = getGuestServiceRequestEmailText({
      guestName: validatedData.guest_name,
      trackingSerial,
      projectTitle: validatedData.title,
      trackingUrl,
      siteUrl,
      createAccountUrl,
    });

    const emailResult = await sendEmail({
      to: validatedData.guest_email,
      subject: `Service Request Confirmation - ${trackingSerial}`,
      html: emailHtml,
      text: emailText,
    });

    if (!emailResult.success) {
      console.error(
        "[GuestServiceRequest] ⚠️ Email NOT sent:",
        emailResult.error
      );
      // Don't fail the request if email fails - user still has tracking serial
    } else {
      console.log(
        "[GuestServiceRequest] ✅ Email sent to:",
        validatedData.guest_email
      );
    }

    return {
      success: true,
      trackingSerial,
      rateLimitInfo: {
        remaining: Math.min(ipLimit.remaining, emailLimit.remaining),
        resetAt: Math.max(ipLimit.resetAt, emailLimit.resetAt),
        resetIn: formatTimeRemaining(
          Math.max(ipLimit.resetAt, emailLimit.resetAt)
        ),
      },
    };
  } catch (error) {
    console.error("[GuestServiceRequest] ❌ Error:", error);

    if (error instanceof Error) {
      // Check if it's a validation error
      if (error.name === "ZodError") {
        return {
          success: false,
          error: "Invalid form data. Please check your inputs and try again.",
        };
      }
      return {
        success: false,
        error: error.message,
      };
    }

    return {
      success: false,
      error: "An unexpected error occurred. Please try again later.",
    };
  }
}

interface GetServiceRequestBySerialResult {
  success: boolean;
  data?: ServiceRequestTracking;
  error?: string;
}

/**
 * Get service request details by tracking serial (public access)
 */
export async function getServiceRequestBySerial(
  input: TrackingSerialInput
): Promise<GetServiceRequestBySerialResult> {
  try {
    // 1. Validate tracking serial format
    const validatedData = trackingSerialSchema.parse(input);

    // 2. Query the public view (limited fields only)
    const supabaseAdmin = getAdminClient();

    const { data, error } = await supabaseAdmin
      .from("service_request_tracking")
      .select("*")
      .eq("tracking_serial", validatedData.tracking_serial)
      .single();

    if (error) {
      if (error.code === "PGRST116") {
        // Not found
        return {
          success: false,
          error: "Tracking serial not found. Please check and try again.",
        };
      }
      throw error;
    }

    return {
      success: true,
      data: data as ServiceRequestTracking,
    };
  } catch (error) {
    console.error("[GetServiceRequestBySerial] Error:", error);

    if (error instanceof Error) {
      if (error.name === "ZodError") {
        return {
          success: false,
          error: "Invalid tracking serial format.",
        };
      }
      return {
        success: false,
        error: error.message,
      };
    }

    return {
      success: false,
      error: "Failed to retrieve service request.",
    };
  }
}

interface LinkGuestRequestToUserResult {
  success: boolean;
  error?: string;
}

/**
 * Link a guest service request to a newly created user account
 * Called after user signs up with the same email as their guest request
 */
export async function linkGuestRequestToUser(
  trackingSerial: string,
  userId: string
): Promise<LinkGuestRequestToUserResult> {
  try {
    const supabaseAdmin = getAdminClient();

    // Call the database function to link the request
    const { data, error } = await supabaseAdmin.rpc(
      "link_guest_request_to_user",
      {
        p_tracking_serial: trackingSerial,
        p_user_id: userId,
      }
    );

    if (error) {
      console.error("[LinkGuestRequest] RPC error:", error);
      throw error;
    }

    if (!data) {
      return {
        success: false,
        error:
          "Could not link request. Email addresses may not match or request already linked.",
      };
    }

    console.log(
      "[LinkGuestRequest] ✅ Successfully linked:",
      trackingSerial,
      "to user:",
      userId
    );

    return {
      success: true,
    };
  } catch (error) {
    console.error("[LinkGuestRequest] Error:", error);
    return {
      success: false,
      error:
        error instanceof Error
          ? error.message
          : "Failed to link service request to account.",
    };
  }
}

/**
 * Get all service requests for a user (authenticated)
 * Includes both originally authenticated requests and converted guest requests
 */
export async function getUserServiceRequests(
  userId: string
): Promise<{ success: boolean; data?: ServiceRequest[]; error?: string }> {
  try {
    const supabaseAdmin = getAdminClient();

    const { data, error } = await supabaseAdmin
      .from("service_requests")
      .select("*")
      .eq("client_id", userId)
      .order("created_at", { ascending: false });

    if (error) {
      throw error;
    }

    return {
      success: true,
      data: data as ServiceRequest[],
    };
  } catch (error) {
    console.error("[GetUserServiceRequests] Error:", error);
    return {
      success: false,
      error:
        error instanceof Error
          ? error.message
          : "Failed to retrieve service requests.",
    };
  }
}

// Made with Bob
